package metrics;

public enum MetricKey {

    NOISEGENERATION,
    CONTINENTGENERATION,
    RIVERGENERATION,
    CITYGENERATION,
    NAMEGENERATION,
    TERRITORYGENERATION,
    TEMPERATUREGENERATION,
    HUMIDITYGENERATION,
    SHADEMAP,
    FANTASYCOLORMAP

}
